### ISSUE TITLE
Expose information on patent policy under which a WG operates

### ISSUE THREAD

**Issue by dontcallmedom** [marcoscaceres/respec.org#108]
In my work towards facilitating transition to Process 2020 in w3c/respec#3086, I'm proposing to add a [new configuration option `wgPatentPolicy`](https://github.com/w3c/respec/pull/3096/commits/229211bfcea2d9e0b55958b47e03fe3447052341) that determines whether a group is operating under Patent Policy 2017 or the newly approved Patent Policy 2020.

Ideally, that information would be determined automatically for specs where the group info is retrieved from the W3C API. It is exposed in the route `https://api.w3.org/groups/<id>/charters` (when embed is set to true) on the last charter, as a property named "patent-policy".

So it would be great if the respec.org cache could expose that value so that the configuration option in ReSpec be determined automatically.

**Comment by sidvishnoi** [comment]
Should we assume the Patent Policy to be 2017 by default? Requiring all specs to specify a `wgPatentPolicy` might be a lot of extra work for maintainers. We can show a warning when it's not set, and assume it to be 2017?

Question: Maybe instead of `groups/<id>/charters`, we could use `/groups/?embed=true` and fetch `_links["active-charter"]` directly?

This change would require some effort on respec.org, as presently we fetch all groups in one go, instead of sending individual request for all groups when needed. I will try to do it over the weekend.
